services:
  - type: web
    name: cniis-website
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true 